version: '3'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/backend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 3000:3000
