name: CI

on: push

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
          check-latest: true
      - name: Download dependencies
        run: go mod download
      - name: Build binary
        run: go build
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: '2022.1.1'

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Eslint
        run: npm run lint
      - name: Jest
        run: npm run test
